- docker-compose.yml
- mirror-intel/Rocket.toml
Now we have fully-synchronized pypi, and we can add back memory limits.
> mirror-intel: limit mem usage

- Makefile
- caddy-gen/caddy-gen.py
- caddy-gen/config.py
- caddy/Caddyfile
- integration-test/.gitignore
- integration-test/siyuan_test.py
- lug/config.yaml
- lug/worker-script/git.sh
This PR also:
* adds `x-sjtug-mirror-id` in header
* expose `linuxbrew-bottles`
* fix llvm-project wrong path
> caddy: fix git redirect, support graceful reload

- common/gai.conf
- docker-compose.yml
It seems that Debian (and alpine) won't use IPv6 nat address by default. By changing `gai.conf` on Debian, we could solve this issue. For Alpine images, I'll work on it later.
> network: prefer ipv6 nat address

- caddy-gen/src/config.py
- caddy/Caddyfile.local
- caddy/Caddyfile.siyuan
- caddy/Caddyfile.zhiyuan
- docker-compose.local.yml
- lug/config.local.yaml
- lug/config.zhiyuan.yaml
Due to a bug in caddy which causes infinite redirection, we make a symbol link of CRAN to cran and serve it as file instead of 302 redirect.
> caddy-gen: fix uppercase url

- caddy-gen/src/caddy-gen.py
- caddy/Caddyfile.siyuan
- caddy/Caddyfile.zhiyuan
Adding speedtest causes all HTTP log disappear. This is because logging is not enabled for speedtest, thus not enabled for all HTTP sites.
We may also wait until https://github.com/caddyserver/caddy/pull/4028 is available, which greatly simplifies logging configuration.
> caddy-gen: fix logging

- config.siyuan.yaml
(Temporarily) Fix https://github.com/sjtug/mirror-requests/issues/181
我们发现 kernel.org 上游可能出现不一致的情况，因此暂时换掉上游。
cc @PhotonQuantum 请帮忙 deploy，感谢。记得用 rebase 模式 git pull。
> lug: update archlinux upstream

- docker-compose.siyuan.yml
From https://github.com/sjtug/mirror-docker-unified/issues/2, we observe about 30 IOPS and 40MB/s (rand) write performance on cloud disk. Based on the statistics, we may be able to give about 1/4 of the total bandwidth to the rsync service.
> docker-compose: lift limit for rsync disk IO

- config.siyuan.yaml
After we fixed HTTP last-modified bug in mirror-clone, we could finally synchronize the kernel repo. Note that the issue is caused by the `#` symbol in the URL foundationally, and we should fix this later.
> lug: enable kernel synchronize

- config.siyuan.yaml
USTC only makes rsync available at rsync.mirrors.ustc.edu.cn
> lug: update homebrew rsync endpoint

- caddy/Dockerfile
Some changes to be done:
* `common_log` will be removed. We must migrate to JSON log. By migrating to JSON log,. we could also filter User-Agent in our ELK stack. https://github.com/caddyserver/caddy/issues/4148
* Use multi issuer support for `ftp.sjtu.edu.cn`, which will fallback to NIC's cert after Let's Encrypt fails. We won't need to use a separate PR to specify certs. https://caddyserver.com/docs/automatic-https#issuer-fallback
> caddy: bump version to 2.4.0

- config.siyuan.yaml
https://github.com/sjtug/mirror-requests/issues/162#issuecomment-855539123 removes the password of openeuler.
> lug: remove openeuler password

- lug/worker-script/mirrorz.py
endpoints.url with https would result in
```
$ curl https://sjtugsiyuan.mirrors.cngi.edu.cn/ -I
HTTP/2 302
location: https://https://mirror.sjtu.edu.cn
```
(tmply fixed on cngi server now)
Also, hyphen is trimmed according to https://github.com/mirrorz-org/mirrorz-302/commit/52b63a3664062e2efe7d20854da7f08da1de0a0d
> Fix mirrorz.d.json

- config.siyuan.yaml
`mirrors.sio.kernel.org` has been out of sync for 5 days.
```
Tue Apr 19 14:56:48 UTC 2022
Date: Tue, 19 Apr 2022 14:56:48 +0000
Date-Started: Tue, 19 Apr 2022 14:42:28 +0000
Archive serial: 2022041903
```
This PR switches our upstream to `sv.mirrors.kernel.org`, which is now the default resolved server for `mirrors.kernel.org` on our host.
> lug: change debian upstream

- caddy/Caddyfile.siyuan
- config.siyuan.yaml
Now that disk1 is full, I'm moving fedora-secondary (approximately 1T) to disk3. After that, both disk1 and disk3 should have about 1T left.
> lug: move fedora-secondary to disk3

- config.zhiyuan.yaml
NLUUG brought down their kali repo, and we accidentally deleted it together with them. I tried syncing from archive-4.kali.org, but it's too slow. JAIST looks like a good alternative.
> fix(lug): sync kali from archive-4.kali.org

- config.siyuan.yaml
`ftp.kr.debian.org` has been down for two days.
> fix(lug): sync debian-ports from ftp.de.debian.org

- caddy/Caddyfile.siyuan
- caddy/Caddyfile.zhiyuan
- config.siyuan.yaml
- config.zhiyuan.yaml
- docker-compose.yml
- lug/worker-script/rsync-fetcher.sh
- rsync-gateway/config.siyuan.toml
Qt now takes up about 1.4T of space, and most of the traffic to Zhiyuan is to this repo. Since Zhiyuan is overloaded, I propose to serve Qt on S3 storage.
I will keep the Qt repository on Zhiyuan for a month as a backup. In case of problems, we can always undo the migration.
> lug: move qt to s3

- config.zhiyuan.yaml
- docker-compose.yml
- lug/worker-script/rsync-fetcher.sh
1. hide qt_rsync from mirror site
2. handle bash escape correctly for rsync-fetcher > rsync_extra_flags
> followups for qt-to-s3

- lug/Dockerfile
- lug/worker-script/apt.sh
As per https://github.com/sjtug/mirror-requests/issues/79#issuecomment-1573295585, we need an apt-mirror script to sync apt repositories from HTTP upstream.
An example config:
```yaml
source: https://apt.pop-os.org
name: popos
arch: all,arm64,amd64
repo: release:jammy:main,release:impish:main
path: /some/path/popos
apt_mirror_path: /some/path/apt_mirror_path
```
`mirror`, `skel` and `var` directories will be created under `apt_mirror_path`, and the `mirror` directory will be symlinked to `path`. `apt_mirror_path` should never be cleaned manually, which `apt-mirror` handles.
Potential problem: does Caddy follow root path symlink? Say caddy is serving `/some/path` while `/some/path` itself is a symlink to another directory.
> lug: apt mirror script

- caddy/Caddyfile.siyuan
- caddy/Caddyfile.zhiyuan
- config.siyuan.yaml
- config.zhiyuan.yaml
- rsync-gateway/config.siyuan.toml
This reverts commit 42c16aa96744d4a5783fb7d08c1a1f3d961049f8.
Now that we've fixed https://github.com/sjtug/rsync-sjtug/issues/11, we can move qt repo back to S3.
> Revert "lug: move qt back to block device (#401)"

- caddy/Caddyfile.siyuan
- caddy/Caddyfile.zhiyuan
- config.siyuan.yaml
- config.zhiyuan.yaml
- rsync-gateway/config.siyuan.toml
This reverts commit a7a07aa85f95c4c03063ad659a3bf1328da1244e.
Unfortunately, the Qt repository's S3 version has been experiencing failures for six days. A thorough investigation is required to identify the root cause, with the primary suspect being the slow speed of metadata diffing and generation.
The issue can likely be resolved with the upcoming release of rsync-sjtug based on Postgres. Until then, we will not be reverting to S3 storage for this repository.
> Revert "Revert "lug: move qt back to block device (#401)" (#404)"

- config.siyuan.yaml
- lug/worker-script/mirrorz.py
Trying to workaround https://github.com/mirrorz-org/mirrorz-help/issues/132.
> lug: add support of adhoc in mirrorz generation

- config.siyuan.yaml
- lug/worker-script/mirrorz.py
#440 again, with compatibility to lug's `Config` struct this time.
>  lug: another try of mirrorz adhoc support 

- caddy/Caddyfile.siyuan
- caddy/Caddyfile.zhiyuan
- config.zhiyuan.yaml
Due to the relatively low usage of the Julia repository in spite of its extraordinary size, we are considering deprecating it or serving it on a cache-by-demand basis.
To ensure a smoother transition, we will redirect this repository to PKU mirror service.
> lug: redirect julia to pku

- config.siyuan.yaml
> 2023-12-18: We had to change the DNS name for rsync to rsync.openwrt.org because downloads.openwrt.org is now served by a CDN. Please update your mirror setup to use the new name.
>
> https://openwrt.org/downloads
> lug: fix openwrt upstream url

- lug/Dockerfile
- rsyncd/rsyncd.siyuan.conf
- rsyncd/rsyncd.zhiyuan.conf
Current settings produces logs below:
```
siyuan-rsyncd  | 2025/08/26 03:19:35 [22457] name lookup failed for 172.19.0.1: Name or service not known
siyuan-rsyncd  | 2025/08/26 03:19:35 [22457] connect from UNKNOWN (172.19.0.1)
```
Disable rDNS lookup to make log clean.
> rsyncd: disable reverse dns lookup

- .github/workflows/lint.yml
- caddy-gen/Pipfile
- caddy-gen/Pipfile.lock
- caddy/Caddyfile.siyuan
- caddy/Caddyfile.zhiyuan
- config.siyuan.yaml
- gateway-gen/Pipfile
- gateway-gen/Pipfile.lock
- integration-test/Pipfile
- integration-test/Pipfile.lock
NOTE: this mirror will soon be dropped, users may fetch from PyPI instead.
Closes https://github.com/sjtug/mirror-requests/issues/370
> lug: redirect intel-extension-for-pytorch to intel-hosted s3
