lug/config.yaml, lug/worker-script/rsync.sh
TODO: use two-stage sync for ubuntu and other apt mirrors (ref: https://wiki.ubuntu.com/Mirrors/Scripts) @doctormin
=> lug: add ubuntu

Makefile, caddy/Caddyfile, docker-compose.yml, lug/config.bootstrap.yaml, lug/config.yaml
This PR changes upstreams of repos that have been bootstrapped to be their original upstream, so as to catch up with the upstream. This PR should be merged after we have synchronized opensuse from ftp.
cc @doctormin should sync the changes in bootstrap config to the production config.
=> lug: change bootstrap settings

docker-compose.yml, lug/config.bootstrap.yaml
We make repos on disk2 sync first, so as to bootstrap faster.
=> lug: change bootstrap config

docker-compose.siyuan.yml, lug/config.siyuan.yaml, mirror-intel/Rocket.toml
related: https://github.com/tuna/issues/issues/1121
=> repos: add gns3/gui

caddy/Caddyfile.siyuan, lug/config.siyuan.yaml, lug/worker-script/mirrorz/siyuan.json, lug/worker-script/mirrorz/zhiyuan.json, mirror-intel/Rocket.toml
https://github.com/oneclick/rubyinstaller2/issues/209
https://github.com/tuna/issues/issues/1136
https://github.com/tuna/issues/issues/1138
=> repos: add PowerShell and rubyinstaller2

docker-compose.yml
https://github.com/gliderlabs/logspout/issues/449 https://github.com/gliderlabs/logspout/pull/501
=> logspout: fix conflict with io limit

.github/workflows/lint.yml, caddy-gen/src/caddy-gen.py, caddy-gen/src/config.py, caddy/Caddyfile.zhiyuan, lug/Dockerfile, lug/build-script/from-cache.sh, lug/build-script/setup-julia-mirror.sh, lug/build-script/setup-julia.sh, lug/build-script/setup-packagist.sh, lug/build-script/setup-php.sh, lug/config.zhiyuan.yaml, mirror-intel/Rocket.toml
=> lug: add tools for zhiyuan

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, docker-compose.yml, lug/config.siyuan.yaml, lug/config.zhiyuan.yaml, mirror-intel/Rocket.toml
https://github.com/sjtug/mirror-intel/pull/50
=> repos: add pypi

caddy-gen/src/caddy-gen.py, caddy-gen/src/repos.py, caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan
fix https://github.com/sjtug/mirror-docker-siyuan/issues/154
=> caddy-gen: fix logging

caddy-gen/src/caddy-gen.py, caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, docker-compose.siyuan.yml, docker-compose.yml, docker-compose.zhiyuan.yml, git-backend/Dockerfile, git-backend/LICENSE, git-backend/nginx.conf, lug/config.zhiyuan.yaml
fix https://github.com/sjtug/mirror-docker-unified/issues/148
=> feat: add git-backend

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, lug/config.siyuan.yaml
https://github.com/sjtug/mirror-requests/issues/20
=> repos: add homebrew/install

caddy/Caddyfile.siyuan, config.siyuan.yaml, config.zhiyuan.yaml
Synchronize anaconda takes lots of memory. We may fix memory issue later. We had to synchronize it on Siyuan server.
=> lug: sync anaconda on siyuan

config.siyuan.yaml, mirror-intel/Rocket.toml
TUNA nano mirrors are going to have maintenance next week. So we switched to the main server.
=> feat: switch to TUNA main server

config.siyuan.yaml
=> feat: fix upstream

caddy-gen/src/caddy-gen.py, caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan
=> caddy-gen: use SJTU git

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml
=> lug: add debian-ports

caddy-gen/src/caddy-gen.py, caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan
=> feat: support speedtest on http

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml
=> lug: add homebrew-bundle.git

lug/worker-script/git.sh
=> worker-script: support git repo without target

config.zhiyuan.yaml
close https://github.com/sjtug/mirror-docker-unified/issues/300
=> lug: limit emacs-elpa speed

caddy-gen/src/caddy-gen.py, caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan
Close https://github.com/sjtug/mirror-requests/issues/221
=> caddy-gen: use ISRG Root X1

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml
=> lug: disable linuxbrew-bottles

caddy-gen/src/caddy-gen.py, caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml, config.zhiyuan.yaml
close https://github.com/sjtug/mirror-docker-unified/issues/309
=> caddy-gen: remove git.sjtu dependency

config.zhiyuan.yaml
close https://github.com/sjtug/mirror-requests/issues/251
=> lug: switch emacs-elpa upstream

lug/worker-script/conda.cloud.yaml
=> lug: fix pytorch-lts

config.siyuan.yaml, config.zhiyuan.yaml, docker-compose.yml, lug/worker-script/mirrorz.py, lug/worker-script/mirrorz.sh
=> mirrorz: add upstream

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml
=> lug: mitigate centos, debian-cd and ubuntu-cd

config.siyuan.yaml
fix https://github.com/sjtug/mirror-requests/issues/261
=> lug: use mirror-clone v2 for rustup

config.siyuan.yaml
=> lug: sync rustup every 12 hrs

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml, lug/worker-script/mirrorz.py, lug/worker-script/mirrorz/siyuan.json, lug/worker-script/mirrorz/zhiyuan.json
close https://github.com/sjtug/mirror-requests/issues/267
=> lug, mirrorz: add source and update mirrorz endpoints

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml
=> lug: remove ubuntu-cd

caddy/Caddyfile.siyuan, config.siyuan.yaml
=> fix: wrong config for archlinuxcn

lug/worker-script/zhiyuan/worker-script/awss3.sh
as per https://github.com/tuna/issues/issues/1593
=> lug(s3): use --exact-timestamps

lug/worker-script/zhiyuan/worker-script/opam.sh
I think:
1. the \n should work together with printf, at least not working with echo
2. `:` should be used instead of =
=> fix opam.sh

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml, config.zhiyuan.yaml, rsync-gateway/config.siyuan.toml
=> lug: move rpi images to s3

config.zhiyuan.yaml, lug/worker-script/mirrorz.py
For crates.io-index and git/crates.io-index
=> mirrorz: link one status to another

config.siyuan.yaml
As per request by Infrastructure team, openEuler community.
=> lug: new rsync endpoint for openeuler

lug/worker-script/mirrorz.py
Ref to https://github.com/mirrorz-org/mirrorz-302/pull/7
=> mirrorz: add geo/isp range

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml, rsyncd/rsyncd.siyuan.conf
Closes https://github.com/sjtug/mirror-requests/issues/223
=> lug: termux

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml
Closes https://github.com/sjtug/mirror-requests/issues/319
=> lug: new mirror immortalwrt

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml, scripts/popos_dists.sh
https://github.com/sjtug/mirror-requests/issues/79
=> lug: new mirror pop-os

config.siyuan.yaml
https://github.com/sjtug/mirror-requests/issues/79#issuecomment-1580325212
=> lug: mirror i386 and src packages of pop-os

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml, rsync-gateway/config.siyuan.toml
https://github.com/sjtug/mirror-requests/issues/236
=> lug: new mirror packman

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml, rsync-gateway/config.siyuan.toml
Fixes https://github.com/sjtug/mirror-requests/issues/214
=> lug: use rsync-fetcher to sync bioconductor

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml, rsync-gateway/config.siyuan.toml
https://github.com/sjtug/mirror-requests/issues/307
=> lug: new mirror debian-cdimage

caddy/Caddyfile.siyuan, caddy/Caddyfile.zhiyuan, config.siyuan.yaml
I am not sure whether I can use second level paths. If that can work as a namespace I think this would be better...
=> lug: add lean4 pkgs

config.siyuan.yaml, docker-compose.yml
=> lug: elan update

config.siyuan.yaml, docker-compose.yml
fixes https://github.com/sjtug/mirror-requests/issues/327
=> lug: fix missing file in debian-cdimage

config.siyuan.yaml, lug/worker-script/mirrorz.py
This reverts commit 30803804dd5ba011bc8f2c102972bfe1a281fe02.
=> Revert "lug: add support of adhoc in mirrorz generation (#440)"

config.siyuan.yaml
Please merge https://github.com/sjtug/mirror-clone/pull/127 and release a new version before merge this PR.
=> elan: add proofwidget

git-backend/Dockerfile, lug/Dockerfile, mirror-intel/Dockerfile, rsync-gateway/Dockerfile, rsyncd/Dockerfile
ftp.sjtu.edu.cn has been out-of-sync for 3 months.
=> lug: build images with ustc upstream
